import type {
  NormalizedPage,
  ApiEndpoint,
  Pitfall,
} from '../../shared/src/index.ts';

export interface LlmsTxtExportData {
  title?: string;
  summary?: string;
  docVersion?: string;
  pages: NormalizedPage[];
  endpoints: ApiEndpoint[];
  pitfalls: Pitfall[];
  full?: boolean;
}

/**
 * Generates an llms.txt (or llms-full.txt) document according to the llms.txt specification.
 * Fully deterministic output.
 */
export function generateLlmsTxt(data: LlmsTxtExportData): string {
  const lines: string[] = [];
  const title = data.title || 'Documentation Index';
  const summary = data.summary || 'Curated machine-readable documentation index generated by DocOrbit.';

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`> ${summary}`);
  lines.push('');

  if (data.docVersion) {
    lines.push(`Documentation Version: \`${data.docVersion}\``);
    lines.push('');
  }

  // 1. Pages / Core Docs
  lines.push('## Documentation Pages');
  lines.push('');
  if (data.pages.length > 0) {
    const sortedPages = [...data.pages].sort((a, b) => a.url.localeCompare(b.url));
    for (const page of sortedPages) {
      const pageTitle = page.title || page.url;
      const tokens = page.estimatedTokens ? ` (~${page.estimatedTokens} tokens)` : '';
      lines.push(`- [${pageTitle}](${page.url})${tokens}`);
    }
    lines.push('');
  } else {
    lines.push('- *No documentation pages indexed.*');
    lines.push('');
  }

  // 2. API Reference
  if (data.endpoints.length > 0) {
    lines.push('## API Reference');
    lines.push('');
    const sortedEndpoints = [...data.endpoints].sort((a, b) => {
      const cmp = a.path.localeCompare(b.path);
      return cmp !== 0 ? cmp : a.method.localeCompare(b.method);
    });

    for (const ep of sortedEndpoints) {
      const desc = ep.summary ? `: ${ep.summary}` : '';
      const provUrl = ep.provenance?.sourceUrl || `#`;
      lines.push(`- [${ep.method.toUpperCase()} ${ep.path}](${provUrl})${desc}`);
    }
    lines.push('');
  }

  // 3. Pitfalls & Warnings
  if (data.pitfalls.length > 0) {
    lines.push('## Critical Caveats & Warnings');
    lines.push('');
    const sortedPitfalls = [...data.pitfalls].sort((a, b) => a.title.localeCompare(b.title));
    for (const pf of sortedPitfalls) {
      const provUrl = pf.provenance?.sourceUrl || `#`;
      lines.push(`- [${pf.title}](${provUrl}): ${pf.message}`);
    }
    lines.push('');
  }

  // If full mode requested, append full page text
  if (data.full) {
    lines.push('---');
    lines.push('## Full Documentation Content');
    lines.push('');
    const sortedPages = [...data.pages].sort((a, b) => a.url.localeCompare(b.url));
    for (const page of sortedPages) {
      lines.push(`### [${page.title || page.url}](${page.url})`);
      lines.push('');
      lines.push(page.content.trim());
      lines.push('');
    }
  }

  return lines.join('\n');
}
