#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// 1. Read package.json
const pkgPath = path.join(rootDir, 'package.json');
const pkgRaw = fs.readFileSync(pkgPath, 'utf-8');
const pkg = JSON.parse(pkgRaw);

// 2. Check if a new version argument was passed (e.g. node scripts/sync-version.js 0.2.1)
const newVersionArg = process.argv[2];
let targetVersion = pkg.version;

if (newVersionArg && newVersionArg !== pkg.version) {
  if (!/^\d+\.\d+\.\d+(-[a-zA-Z0-9.]+)?$/.test(newVersionArg)) {
    console.error(`[docorbit:version] Error: Invalid semver version format: ${newVersionArg}`);
    process.exit(1);
  }
  targetVersion = newVersionArg;
  pkg.version = targetVersion;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
  console.log(`[docorbit:version] Updated package.json version to ${targetVersion}`);
}

// 3. Update packages/shared/src/version.ts
const sharedVersionPath = path.join(rootDir, 'packages/shared/src/version.ts');
const sharedVersionContent = `/**
 * Auto-generated by scripts/sync-version.js. Do not edit directly.
 * Single source of truth is package.json.
 */
export const DOCORBIT_VERSION = '${targetVersion}';
`;
fs.writeFileSync(sharedVersionPath, sharedVersionContent, 'utf-8');

// 4. Update site/index.html
const indexHtmlPath = path.join(rootDir, 'site/index.html');
if (fs.existsSync(indexHtmlPath)) {
  let html = fs.readFileSync(indexHtmlPath, 'utf-8');
  html = html.replace(/DocOrbit v\d+\.\d+\.\d+(?:-[a-zA-Z0-9.]+)? released/g, `DocOrbit v${targetVersion} released`);
  html = html.replace(/<span class="brand-badge">v\d+\.\d+\.\d+(?:-[a-zA-Z0-9.]+)?<\/span>/g, `<span class="brand-badge">v${targetVersion}</span>`);
  html = html.replace(/docorbit-ast-inspector \/\/ v\d+\.\d+\.\d+(?:-[a-zA-Z0-9.]+)?/g, `docorbit-ast-inspector // v${targetVersion}`);
  html = html.replace(/DocOrbit \(v\d+\.\d+\.\d+(?:-[a-zA-Z0-9.]+)?\)/g, `DocOrbit (v${targetVersion})`);
  fs.writeFileSync(indexHtmlPath, html, 'utf-8');
}

// 5. Update site/docs.html and site/docs/index.html
for (const docsRel of ['site/docs.html', 'site/docs/index.html']) {
  const docsPath = path.join(rootDir, docsRel);
  if (fs.existsSync(docsPath)) {
    let html = fs.readFileSync(docsPath, 'utf-8');
    html = html.replace(/<span class="brand-badge">v\d+\.\d+\.\d+(?:-[a-zA-Z0-9.]+)?<\/span>/g, `<span class="brand-badge">v${targetVersion}</span>`);
    fs.writeFileSync(docsPath, html, 'utf-8');
  }
}

console.log(`✔ [docorbit:version] Synced version ${targetVersion} across package.json, shared/version.ts, CLI, and site documentation.`);
